name: Pytest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  conda-test:
    name: Conda tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test
    - name: Install dependencies
      run: |
        pip install -U -r requirements.txt -c constraints.txt
    - name: Lint with pylint and pycodestyle
      run: |
        pip install -U -r requirements-dev.txt -c constraints.txt
        python setup.py build_ext --inplace
        pylint -rn mthree
        pycodestyle --max-line-length=100 mthree
    - name: Run tests with pytest
      run: |
        pip install pytest
        conda install 'numpy>=2'
        pip install .
        pytest -p no:warnings --pyargs mthree/test
    - name: Build docs
      run: |
        conda install pandoc
        cd docs
        make html
