name: Release Artifacts
on:
  push:
    tags:
      - '*'
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest -p no:warnings --pyargs {package}/mthree/tests
          CIBW_ENVIRONMENT: MTHREE_OPENMP=1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
      - name: Publish to PyPi
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: nonhermitian
        run: twine upload ./wheelhouse/*whl
  sdist-build:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Install Deps
        run: pip install -U twine cython numpy
      - name: Build Artifacts
        run: |
          python setup.py sdist
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/mthree*
      - name: Publish to PyPi
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: nonhermitian
        run: twine upload dist/mthree*
