name: Release Artifacts
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest -p no:warnings --pyargs {package}/mthree/tests
          CIBW_ENVIRONMENT: MTHREE_OPENMP=1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
